version: "2"
services:
  manufaq-site-prod:
    build:
      context: .
      args:
        API_HOST: ${API_HOST}
    image: manufaqtury_site:${REVISION}
    networks:
      - reverse-proxy
    expose:
      - 3000
    ports:
      - 3131:3000
    environment:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: ${BASE_APP_HOST_BUILD}
      LETSENCRYPT_HOST: ${BASE_APP_HOST_BUILD}
      LETSENCRYPT_EMAIL: https@obvu.ru
      NUXT_HOST: 0.0.0.0
      API_HOST: ${API_HOST}
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
